// Code generated by "stringer -type=Key"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[authservice-0]
	_ = x[cockroach-1]
	_ = x[gatewaymt-2]
	_ = x[linksharing-3]
	_ = x[redis-4]
	_ = x[satelliteadmin-5]
	_ = x[satelliteapi-6]
	_ = x[satellitecore-7]
	_ = x[storagenode-8]
	_ = x[uplink-9]
	_ = x[versioncontrol-10]
	_ = x[storjscan-11]
	_ = x[geth-12]
	_ = x[prometheus-13]
	_ = x[grafana-14]
	_ = x[appbasedev-15]
	_ = x[appbaseubuntu-16]
	_ = x[appedge-17]
	_ = x[appstorj-18]
}

const _Key_name = "authservicecockroachgatewaymtlinksharingredissatelliteadminsatelliteapisatellitecorestoragenodeuplinkversioncontrolstorjscangethprometheusgrafanaappbasedevappbaseubuntuappedgeappstorj"

var _Key_index = [...]uint8{0, 11, 20, 29, 40, 45, 59, 71, 84, 95, 101, 115, 124, 128, 138, 145, 155, 168, 175, 183}

func (i Key) String() string {
	if i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
