// Code generated by "stringer -type=Key"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[authservice-0]
	_ = x[cockroach-1]
	_ = x[gatewaymt-2]
	_ = x[linksharing-3]
	_ = x[redis-4]
	_ = x[satelliteadmin-5]
	_ = x[satelliteapi-6]
	_ = x[satellitecore-7]
	_ = x[storagenode-8]
	_ = x[uplink-9]
	_ = x[versioncontrol-10]
	_ = x[prometheus-11]
	_ = x[grafana-12]
	_ = x[appbasedev-13]
	_ = x[appbaseubuntu-14]
	_ = x[appedge-15]
	_ = x[appstorj-16]
	_ = x[traefik-17]
}

const _Key_name = "authservicecockroachgatewaymtlinksharingredissatelliteadminsatelliteapisatellitecorestoragenodeuplinkversioncontrolprometheusgrafanaappbasedevappbaseubuntuappedgeappstorjtraefik"

var _Key_index = [...]uint8{0, 11, 20, 29, 40, 45, 59, 71, 84, 95, 101, 115, 125, 132, 142, 155, 162, 170, 177}

func (i Key) String() string {
	if i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
