// AUTOGENERATED BY pkg/config/gen
// DO NOT EDIT.

package config

func authserviceConfig() []Option {
	return []Option{
		
		{
			Name:        "STORJ_ENDPOINT",
			Description: "Gateway endpoint URL to return to clients",
			Default:     "",
		},
		{
			Name:        "STORJ_AUTH_TOKEN",
			Description: "auth security token(s) to validate requests",
			Default:     "",
		},
		{
			Name:        "STORJ_POSTSIZE_LIMIT",
			Description: "maximum size that the incoming POST request body with access grant can be",
			Default:     "4KiB",
		},
		{
			Name:        "STORJ_ALLOWED_SATELLITES",
			Description: "list of satellite NodeURLs allowed for incoming access grants",
			Default:     "https://www.storj.io/dcs-satellites",
		},
		{
			Name:        "STORJ_CACHE_EXPIRATION",
			Description: "length of time satellite addresses are cached for",
			Default:     "10m",
		},
		{
			Name:        "STORJ_SHUTDOWN_DELAY",
			Description: "time to delay server shutdown while returning 503s on the health endpoint",
			Default:     "",
		},
		{
			Name:        "STORJ_IDLE_TIMEOUT",
			Description: "timeout for idle connections",
			Default:     "60s",
		},
		{
			Name:        "STORJ_KVBACKEND",
			Description: "key/value store backend url",
			Default:     "",
		},
		{
			Name:        "STORJ_MIGRATION",
			Description: "create or update the database schema, and then continue service startup",
			Default:     "false",
		},
		{
			Name:        "STORJ_LISTEN_ADDR",
			Description: "public HTTP address to listen on",
			Default:     ":20000",
		},
		{
			Name:        "STORJ_LISTEN_ADDR_TLS",
			Description: "public HTTPS address to listen on",
			Default:     ":20001",
		},
		{
			Name:        "STORJ_DRPCLISTEN_ADDR",
			Description: "public DRPC address to listen on",
			Default:     ":20002",
		},
		{
			Name:        "STORJ_DRPCLISTEN_ADDR_TLS",
			Description: "public DRPC+TLS address to listen on",
			Default:     ":20003",
		},
		{
			Name:        "STORJ_PROXY_ADDR_TLS",
			Description: "TLS address to listen on for PROXY protocol requests",
			Default:     ":20005",
		},
		{
			Name:        "STORJ_CERT_FILE",
			Description: "server certificate file",
			Default:     "",
		},
		{
			Name:        "STORJ_KEY_FILE",
			Description: "server key file",
			Default:     "",
		},
		{
			Name:        "STORJ_PUBLIC_URL",
			Description: "comma separated list of public urls for the server TLS certificates (e.g. https://auth.example.com,https://auth.us1.example.com)",
			Default:     "",
		},
		{
			Name:        "STORJ_RETRIEVE_PROJECT_INFO",
			Description: "retrieve and store project info (such as public ID, and created date) when registering access grant",
			Default:     "true",
		},
		{
			Name:        "STORJ_FREE_TIER_ACCESS_LIMIT_MAX_DURATION",
			Description: "maximum amount of time that free tier users' access grants are allowed to be active for. 0 means no limit",
			Default:     "0",
		},
		{
			Name:        "STORJ_FREE_TIER_ACCESS_LIMIT_TIER_QUERY_IDENTITY_CERT_PATH",
			Description: "path to the certificate chain for this identity",
			Default:     "$IDENTITYDIR/identity.cert",
		},
		{
			Name:        "STORJ_FREE_TIER_ACCESS_LIMIT_TIER_QUERY_IDENTITY_KEY_PATH",
			Description: "path to the private key for this identity",
			Default:     "$IDENTITYDIR/identity.key",
		},
		{
			Name:        "STORJ_FREE_TIER_ACCESS_LIMIT_TIER_QUERY_CACHE_EXPIRATION",
			Description: "expiration time for entries in the tier-querying service cache",
			Default:     "5m",
		},
		{
			Name:        "STORJ_FREE_TIER_ACCESS_LIMIT_TIER_QUERY_CACHE_CAPACITY",
			Description: "capacity of the tier-querying service cache",
			Default:     "10000",
		},
		{
			Name:        "STORJ_CERT_MAGIC_ENABLED",
			Description: "use CertMagic to handle TLS certificates",
			Default:     "false",
		},
		{
			Name:        "STORJ_CERT_MAGIC_KEY_FILE",
			Description: "path to the service account key file",
			Default:     "",
		},
		{
			Name:        "STORJ_CERT_MAGIC_EMAIL",
			Description: "email address to use when creating an ACME account",
			Default:     "",
		},
		{
			Name:        "STORJ_CERT_MAGIC_STAGING",
			Description: "use staging CA endpoints",
			Default:     "",
		},
		{
			Name:        "STORJ_CERT_MAGIC_BUCKET",
			Description: "bucket to use for certificate storage with optional prefix (bucket/prefix)",
			Default:     "",
		},
		{
			Name:        "STORJ_NODE_FIRST_START",
			Description: "allow start with empty storage",
			Default:     "",
		},
		{
			Name:        "STORJ_NODE_PATH",
			Description: "path where to store data",
			Default:     "",
		},
		{
			Name:        "STORJ_NODE_CONFLICT_BACKOFF_DELAY",
			Description: "The active time between retries, typically not set",
			Default:     "0ms",
		},
		{
			Name:        "STORJ_NODE_CONFLICT_BACKOFF_MAX",
			Description: "The maximum total time to allow retries",
			Default:     "5m",
		},
		{
			Name:        "STORJ_NODE_CONFLICT_BACKOFF_MIN",
			Description: "The minimum time between retries",
			Default:     "100ms",
		},
		{
			Name:        "STORJ_SPANNER_DATABASE_NAME",
			Description: "name of Cloud Spanner database in the form projects/PROJECT_ID/instances/INSTANCE_ID/databases/DATABASE_ID",
			Default:     "",
		},
		{
			Name:        "STORJ_SPANNER_CREDENTIALS_FILENAME",
			Description: "credentials file with access to Cloud Spanner database",
			Default:     "",
		},
		{
			Name:        "STORJ_SPANNER_ADDRESS",
			Description: "",
			Default:     "",
		},
   }
}
