// AUTOGENERATED BY pkg/config/gen
// DO NOT EDIT.

package config

func storjscanConfig() []Option {
	return []Option{
		
		{
			Name:        "STORJ_DEBUG_ADDR",
			Description: "address to listen on for debug endpoints",
			Default:     "127.0.0.1:0",
		},
		{
			Name:        "STORJ_DEBUG_CONTROL_TITLE",
			Description: "",
			Default:     "",
		},
		{
			Name:        "STORJ_DEBUG_CONTROL",
			Description: "",
			Default:     "",
		},
		{
			Name:        "STORJ_DEBUG_CRAWLSPACE",
			Description: "if true, enable crawlspace on debug port",
			Default:     "false",
		},
		{
			Name:        "STORJ_EVENTS_ADDRESS_BATCH_SIZE",
			Description: "number of Addresses to fetch new events for in a single request",
			Default:     "100",
		},
		{
			Name:        "STORJ_EVENTS_BLOCK_BATCH_SIZE",
			Description: "number of blocks to fetch new events for in a single request",
			Default:     "5000",
		},
		{
			Name:        "STORJ_EVENTS_CHAIN_REORG_BUFFER",
			Description: "minimum number of blocks to re-query for when looking for new transfer events",
			Default:     "15",
		},
		{
			Name:        "STORJ_EVENTS_MAXIMUM_QUERY_SIZE",
			Description: "maximum number of blocks prior to the latest block that storjscan can query for",
			Default:     "10000",
		},
		{
			Name:        "STORJ_TOKENS_ENDPOINTS",
			Description: "List of RPC endpoints [{Name:<Name>,URL:<URL>,Contract:<Contract Address>,ChainID:<Chain ID>},...]",
			Default:     "",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_INTERVAL",
			Description: "how often to run the chore",
			Default:     "1m",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_PRICE_WINDOW",
			Description: "max allowable duration between the requested and available ticker price timestamps",
			Default:     "1m",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_COINMARKETCAP_CONFIG_BASE_URL",
			Description: "base URL for ticker price API",
			Default:     "https://pro-api.coinmarketcap.com",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_COINMARKETCAP_CONFIG_APIKEY",
			Description: "API Key used to access coinmarketcap",
			Default:     "",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_COINMARKETCAP_CONFIG_TIMEOUT",
			Description: "coinmarketcap API response timeout",
			Default:     "10s",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_USE_TEST_PRICES",
			Description: "use test prices instead of coninmaketcap",
			Default:     "false",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_CLEANUP_INTERVAL",
			Description: "how often to remove old token prices",
			Default:     "336h",
		},
		{
			Name:        "STORJ_TOKEN_PRICE_CLEANUP_RETAIN_DAYS",
			Description: "number of days of token prices to retain",
			Default:     "30",
		},
		{
			Name:        "STORJ_HEADER_CLEANUP_INTERVAL",
			Description: "how often to remove old block headers",
			Default:     "336h",
		},
		{
			Name:        "STORJ_HEADER_CLEANUP_RETAIN_DAYS",
			Description: "number of days of block headers to retain",
			Default:     "30",
		},
		{
			Name:        "STORJ_API_ADDRESS",
			Description: "public address to listen on",
			Default:     ":10000",
		},
		{
			Name:        "STORJ_API_KEYS",
			Description: "List of user:secret pairs to connect to service endpoints.",
			Default:     "",
		},
   }
}
