#!/usr/bin/env bash
set -x
check-copyright
check-large-files
check-imports ./...
check-peer-constraints
check-atomic-align ./...
check-errs ./...
check-monkit ./...
staticcheck ./...
golangci-lint -j=2 run
check-mod-tidy -mod .build/go.mod.orig
